#!/usr/bin/env python

import methods

Import('env')
Import('env_modules')

env_sdl = env_modules.Clone()

excludes = [
    '/wayland',
    '/winmm',
    '/windows',
    '/winrt',
    '/haiku',
    '/android',
    '/kmsdrm',
    '/cocoa',
    '/emscripten',
    '/macosx',
    '/mir',
    '/qnx',
    '/nacl',
    '/directfb',
    '/psp',
    '/raspberry',
    '/pandora',
    '/stdcpp',
    'src/test',
    'src/haptic',
    '/dynapi'
]

thirdparty_sources = methods.detect_files("../../thirdparty/SDL2/src", excludes, ['c', 'cc', 'cpp'])

env_sdl.Append(CPPDEFINES=['__LINUX__'])

# TODO try to use -> "#thirdparty/SDL2/include"
env_sdl.Append(CPPPATH=["../../thirdparty/SDL2/include"])

# Thirdparty source files
env_thirdparty_sdl = env_sdl.Clone()
env_thirdparty_sdl.disable_warnings()
env_thirdparty_sdl.add_source_files(env.modules_sources, thirdparty_sources)

# Sdl source files
env_sdl.add_source_files(env.modules_sources, "*.cpp")
