#!/usr/bin/env python

import methods

Import('env')

env_core = env.Clone()

env_core.core_sources = []

Export("env_core")

# Add all thirdparty library used by the core
thirdparty_misc_sources = methods.detect_files("../thirdparty/misc", [], ['c', 'cc', 'cpp'])
env_core.add_source_files(env_core.core_sources, thirdparty_misc_sources)

# Add core cpp files
env_core.add_source_files(env_core.core_sources, "*.cpp")

# Execute math scsub scritp
SConscript("math/SCsub")

lib = env_core.add_library("core", env_core.core_sources)
env.Prepend(LIBS=[lib])
