#!/usr/bin/env python

Import('env')

env_core = env.Clone()

Export("env_core")

env_core.core_sources = []

env_core.add_source_files(env_core.core_sources, "*.cpp")

lib = env_core.add_library("core", env_core.core_sources)
env.Prepend(LIBS=[lib])
