#!/usr/bin/env python

import methods

Import('env')
Import('env_modules')

env_glfw = env_modules.Clone()

excludes = [
'cocoa_',
'win32_',
'wl_',
'null_',
'wgl_',
]

thirdparty_sources = methods.detect_files("../../thirdparty/glfw/src", excludes, ['c', 'cc', 'cpp'])

env_glfw.Append(CPPDEFINES=['_GLFW_X11'])

env_glfw.Append(CPPPATH=["#thirdparty/glfw/include"])

# Thirdparty source files
env_thirdparty_glfw = env_glfw.Clone()
env_thirdparty_glfw.disable_warnings()
env_thirdparty_glfw.add_source_files(env.modules_sources, thirdparty_sources)

# Add library dependecy of GLFW
env.Append(LIBS=['X11'])
env.Append(LIBS=['dl'])
env.Append(LIBS=['pthread'])

# Sdl source files
env_glfw.add_source_files(env.modules_sources, "*.cpp")
